# Generated by Django 4.0.4 on 2022-06-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_about_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='herosec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('list1', models.CharField(max_length=100)),
                ('list2', models.CharField(max_length=100)),
                ('list3', models.CharField(max_length=100)),
                ('list4', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='herosec2/')),
            ],
        ),
    ]
