# Generated by Django 4.0.4 on 2022-06-10 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_features_fleetmap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='features',
            old_name='list1',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='features',
            old_name='list2',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='features',
            old_name='list3',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='features',
            name='list4',
        ),
        migrations.RemoveField(
            model_name='features',
            name='list5',
        ),
        migrations.RemoveField(
            model_name='features',
            name='list6',
        ),
        migrations.RemoveField(
            model_name='features',
            name='list7',
        ),
        migrations.RemoveField(
            model_name='features',
            name='list8',
        ),
        migrations.RemoveField(
            model_name='features',
            name='list9',
        ),
        migrations.AddField(
            model_name='features',
            name='about',
            field=models.CharField(default=django.utils.timezone.now, max_length=700),
            preserve_default=False,
        ),
    ]
