# Generated by Django 4.0.4 on 2022-06-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_rename_list1_features_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='features',
            new_name='footerinfo',
        ),
    ]
