# Generated by Django 4.0.4 on 2022-06-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_delete_footerinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='iridummap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='iridium/')),
            ],
        ),
    ]
