# Generated by Django 4.0.4 on 2022-06-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_iridummap'),
    ]

    operations = [
        migrations.CreateModel(
            name='shipdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='iridium/')),
            ],
        ),
    ]
