# Generated by Django 4.0.4 on 2022-05-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='whyus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='whyus/')),
                ('title', models.CharField(max_length=200)),
                ('discription', models.TextField(max_length=1800)),
            ],
        ),
        migrations.DeleteModel(
            name='cards',
        ),
    ]
