# Generated by Django 4.0.4 on 2022-06-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_whyus_delete_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='whyusinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('discription', models.TextField(max_length=1800)),
            ],
        ),
    ]
