# Generated by Django 4.0.4 on 2022-06-06 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='slider'),
            preserve_default=False,
        ),
    ]
