# Generated by Django 4.0.4 on 2022-06-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_contactlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='footerinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=700)),
            ],
        ),
    ]
