# Generated by Django 4.0.4 on 2022-06-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_footerinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerinfo',
            name='about',
            field=models.TextField(max_length=700),
        ),
    ]
